#!/bin/bash
# blind-test-generator.sh
# Script to run the Blind Test Generator

# Activate virtual environment
source .venv/bin/activate

# Run the Python script with all arguments passed to this script
python src/blind_test_generator.py "$@"